kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-delay
spec:
  template:
    spec:
      containers:
        - name: container
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1