kind: Deployment
apiVersion: apps/v1
metadata:
  name: service-interconnect
spec:
  template:
    spec:
      containers:
        - name: container
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /connect
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 1
            successThreshold: 1
            timeoutSeconds: 3